Vagrant.require_version ">= 1.5"

required_plugins = %w( vagrant-vbguest )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|

    config.vm.box     = "centos/7"
    config.ssh.forward_agent = true

    config.vm.synced_folder "../ansible", "/ansible",
        type: "nfs",
        nfs_export: true

    config.vm.synced_folder "../share/www", "/var/www",
        type: "nfs",
        nfs_export: true

    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "4"]
    end

    config.vm.define "web", primary: true do |web|
      web.vm.network :private_network, ip: "192.168.33.50"
      web.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
      web.vm.network :forwarded_port, guest: 443, host: 8081, auto_correct: true
      web.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true
      web.vm.network :forwarded_port, guest: 15672, host: 15672, auto_correct: true
      web.vm.network :forwarded_port, guest: 5672, host: 5672, auto_correct: true
      web.vm.network :forwarded_port, guest: 9200, host: 9200, auto_correct: true
      web.vm.network :forwarded_port, guest: 5601, host: 5601, auto_correct: true

      web.vm.hostname = "ansibleMpwar"

      web.vm.provision :shell, path: "shell/vagrant_main_provision.sh"
    end
end
